name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Cache Maven pour éviter les re-téléchargements
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Maven
        run: mvn clean package -DskipTests

      # SAST
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Install Snyk CLI
      - name: Install Snyk
        uses: snyk/actions/setup@master

      # SCA — Fix mémoire + auth explicite
      - name: Snyk dependency scan
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          node --max-old-space-size=4096 $(which snyk) test \
            --all-projects \
            --severity-threshold=high \
            --json-file-output=snyk-results.json || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload Snyk results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: snyk-results
          path: snyk-results.json

      # Docker build
      - name: Build Docker image
        run: docker build -t secure-java-app .

      # Container scan
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: secure-java-app
          severity: CRITICAL,HIGH
          exit-code: 1